namespace Tests.Mockaroo
{
	public class MockarooSchemaSpec
	{
		public string BitcoinAddressField { get; set; }
		public string BlankField { get; set; } = "";
		public string BooleanField { get; set; }
		public string CityField { get; set; }
		public string ColorField { get; set; }
		public string CompanyNameField { get; set; }
		public string CountryField { get; set; }
		public string CountryCodeField { get; set; }
		public string CreditCardNumberField { get; set; }
		public string CreditCardTypeField { get; set; }
		public string CurrencyField { get; set; }
		public string CurrencyCodeField { get; set; }
		public string CustomListField { get; set; }
		public string DatasetColumnField { get; set; }
		public string DateField { get; set; }
		public string DomainNameField { get; set; }
		public string DrugCompanyField { get; set; }
		public string DrugNameBrandField { get; set; }
		public string DrugNameGenericField { get; set; }
		public string EmailAddressField { get; set; }
		public string EncryptField { get; set; }
		public string FamilyNameChineseField { get; set; }
		public string FDANDCCodeField { get; set; }
		public string FileNameField { get; set; }
		public string FirstNameField { get; set; }
		public string FirstNameEuropeanField { get; set; }
		public string FirstNameFemaleField { get; set; }
		public string FirstNameMaleField { get; set; }
		public string FormulaField { get; set; }
		public string FrequencyField { get; set; }
		public string FullNameField { get; set; }
		public string GenderField { get; set; }
		public string GenderAbbreviatedField { get; set; }
		public string GivenNameChineseField { get; set; }
		public string GUIDField { get; set; }
		public string HexColorField { get; set; }
		public string IBANField { get; set; }
		public string ICD9DiagnosisCodeField { get; set; }
		public string ICD9DxDescLongField { get; set; }
		public string ICD9DxDescShortField { get; set; }
		public string ICD9ProcDescLongField { get; set; }
		public string ICD9ProcDescShortField { get; set; }
		public string ICD9ProcedureCodeField { get; set; }
		public string IPAddressV4Field { get; set; }
		public string IPAddressV6Field { get; set; }
		public string ISBNField { get; set; }
		public string JobTitleField { get; set; }
		public string JSONArrayField { get; set; }
		public string LanguageField { get; set; }
		public string LastNameField { get; set; }
		public string LatitudeField { get; set; }
		public string LinkedInSkillField { get; set; }
		public string LongitudeField { get; set; }
		public string MACAddressField { get; set; }
		public string MIMETypeField { get; set; }
		public string MoneyField { get; set; }
		public string MongoDBObjectIDField { get; set; }
		public string NaughtyStringField { get; set; }
		public string NormalDistributionField { get; set; }
		public string NumberField { get; set; }
		public string ParagraphsField { get; set; }
		public string PasswordField { get; set; }
		public string PhoneField { get; set; }
		public string PostalCodeField { get; set; }
		public string RaceField { get; set; }
		public string RegularExpressionField { get; set; }
		public string RowNumberField { get; set; }
		public string ScenarioField { get; set; }
		public string SentencesField { get; set; }
		public string SequenceField { get; set; }
		public string ShirtSizeField { get; set; }
		public string ShortHexColorField { get; set; }
		public string SQLExpressionField { get; set; }
		public string SSNField { get; set; }
		public string StateField { get; set; }
		public string StateAbbreviatedField { get; set; }
		public string StreetAddressField { get; set; }
		public string StreetNameField { get; set; }
		public string StreetNumberField { get; set; }
		public string StreetSuffixField { get; set; }
		public string SuffixField { get; set; }
		public string TemplateField { get; set; }
		public string TimeField { get; set; }
		public string TimeZoneField { get; set; }
		public string TitleField { get; set; }
		public string TopLevelDomainField { get; set; }
		public string URLField { get; set; }
		public string UserAgentField { get; set; }
		public string UserNameField { get; set; }
		public string WordsField { get; set; }
	}
}
